const events: any = {
  CREATED: 'CREATED:POST',
  UPDATED: 'UPDATED:PUT',
  DELETED: 'DELETED:DELETE',
  FETCHED: 'FETCHED:GET',
  PROMOTED: 'PROMOTED:POST',
  DEMOTED: 'DEMOTED:DELETE',
  FETCH_USERS: 'FETCH_USERS:GET',
  FETCH_USER: 'FETCH_USER:GET',
  ADDED: 'ADDED:POST',
  REMOVED: 'REMOVED:DELETE',
  BANNED: 'BANNED:POST',
  REGISTERED: 'REGISTERED:POST',
  LOGGED_IN: 'LOGGED_IN:POST',
  LOGGED_OUT: 'LOGGED_OUT:POST',
};

export default events;
