spring:
  datasource:
    url: jdbc:mysql://${DB_HOST:localhost}:3306/genericauth
    username: ${DB_USERNAME:saroj}
    password: ${DB_PASSWORD:saroj}
  tomcat:
    max-wait: 20000
    max-active: 50
    max-idle: 20
    min-idle: 15
  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5InnoDBDialect
        format_sql: true
        id:
          new_generator_mappings: false

server:
  port: 8080

env:
  spring-env: development