spring:
  app-name: Generic Auth
  version: 1.0.0
  datasource:
    url: jdbc:postgresql://${DB_HOST:localhost}:${DB_PORT:5432}/${DB_NAME:genericks}
    username: ${DB_USERNAME:user}
    password: ${DB_PASSWORD:pass}
    driverClassName: org.postgresql.Driver
  tomcat:
    max-wait: 20000
    max-active: 50
    max-idle: 20
    min-idle: 15
  jackson:
    serialization:
      fail-on-empty-beans: false
  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
        id:
          new_generator_mappings: false

server:
  port: ${PORT:8080}
  env: ${SPRING_ENV:development}
  secret: wd^=I3w0%/{ecrX8o)XZQo{_&L@8m#6iD
  error:
    whitelabel:
      enabled: false

smtp:
  port: 587
  server: smtp-relay.sendinblue.com
  username: sarojpaudyal53@gmail.com
  password: Fk2MYfbSrHxs1BEU

aws:
  region: ${AWS_REGION:null}
  bucketName: ${AWS_BUCKET_NAME:null}
  accessKeyId: ${AWS_ACCESS_KEY_ID:null}
  secretAccessKey: ${AWS_SECRET_ACCESS_KEY:null}

logging:
  level:
    org:
      springframework:
        web: debug
