version: 2.1
orbs:
  aws-s3: circleci/aws-s3@1.0.11
jobs:
  server_heroku_push:
    docker:
      - image: circleci/openjdk:8-jdk

    working_directory: ~/repo/server

    environment:
      JVM_OPTS: -Xmx3200m
      TERM: dumb

    steps:
      - setup_remote_docker:
          docker_layer_caching: false

      - checkout:
          path: ~/repo

      # Download and cache dependencies
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "build.gradle" }}
            # fallback to using the latest cache if no exact match is found
            - v1-dependencies-

      - run: gradle dependencies

      - save_cache:
          paths:
            - ~/.gradle
          key: v1-dependencies-{{ checksum "build.gradle" }}

      - run: gradle test

      - run: gradle bootJar

      - run:
          name: "Heroku Install"
          command: |
            if [[ $(command -v heroku) == "" ]]; then
            curl https://cli-assets.heroku.com/install.sh | sh
            else
            echo "Heroku already exists!"
            fi
      - run:
          name: Login into Heroku Docker Repository
          command: |
            docker login --username=$HEROKU_LOGIN --password=$HEROKU_API_KEY registry.heroku.com

      - deploy:
          name: "Deploy Container to Heroku"
          command: "bash scripts/deploy-server.sh"

  app_s3_sync:

    docker:
      - image: circleci/node:12.9.1-browsers

    working_directory: ~/repo/app

    steps:
      - setup_remote_docker:
          docker_layer_caching: false

      - checkout:
          path: ~/repo

      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "package.json" }}
            - v1-dependencies-

      - run: yarn install

      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}

      - run:
          name: Run tests
          command: |
            source ~/.bashrc;
            yarn test;

      - run:
          name: Build the app.
          command: |
            source ~/.bashrc;
            yarn build;
      
      - aws-s3/sync:
          from: build
          to: "s3://www.hamroauth.cf/"
          arguments: |
            --acl public-read \
            --cache-control "max-age=86400"
          overwrite: true

workflows:
  version: 2
  deploy_server:
    jobs:
      - server_heroku_push:
          context:
            - aws
          filters:
            branches:
              only:
                - dev
                - master
  deploy_app:
    jobs:
      - app_s3_sync:
          context:
            - aws
          filters:
            branches:
              only:
                - dev
                - master
