version: 2
jobs:
  server_heroku_push:
    docker:
      - image: circleci/openjdk:8-jdk

    working_directory: ~/repo/server

    environment:
      JVM_OPTS: -Xmx3200m
      TERM: dumb

    steps:
      - setup_remote_docker:
          docker_layer_caching: false

      - checkout:
          path: ~/repo

      # Download and cache dependencies
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "build.gradle" }}
            # fallback to using the latest cache if no exact match is found
            - v1-dependencies-

      - run: gradle dependencies

      - save_cache:
          paths:
            - ~/.gradle
          key: v1-dependencies-{{ checksum "build.gradle" }}

      - run: gradle test

      - run: gradle bootJar

      - run:
          name: "Heroku Install"
          command: |
            if [[ $(command -v heroku) == "" ]]; then
            curl https://cli-assets.heroku.com/install.sh | sh
            else
            echo "Heroku already exists!"
            fi
      - run:
          name: Login into Heroku Docker Repository
          command: |
            docker login --username=$HEROKU_LOGIN --password=$HEROKU_API_KEY registry.heroku.com

      - deploy:
          name: "Deploy Container to Heroku"
          command: "bash scripts/deploy-server.sh"

  app_s3_sync:

    docker:
      - image: circleci/node:12.9.1-browsers

    working_directory: ~/repo/app

    steps:
      - setup_remote_docker:
          docker_layer_caching: false

      - checkout:
          path: ~/repo

      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "package.json" }}
            - v1-dependencies-

      - run: yarn install

      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}

      - run:
          name: Run tests
          command: |
            source ~/.bashrc;
            yarn test;

      - run:
          name: Sync Build Files to S3 Bucket
          command: |
            source ~/.bashrc;
            sudo apt-get update && sudo apt-get install -y python-dev;
            sudo curl -O https://bootstrap.pypa.io/get-pip.py;
            sudo python get-pip.py;
            sudo pip install awscli --upgrade;
            yarn build;
            aws s3 sync build/ s3://www.hamroauth.ml --delete;

workflows:
  version: 2
  deploy_server:
    jobs:
      - server_heroku_push:
          filters:
            branches:
              only:
                - dev
                - master
  deploy_app:
    jobs:
      - app_s3_sync:
          filters:
            branches:
              only:
                - dev
                - master
